[deps]
Bonito = "824d6782-a2ef-11e9-3a09-e5662e0c26f8"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
MeshCat = "283c5d60-a78f-5afe-a0af-af636b173e11"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
Meshing = "e6723b4c-ebff-59f1-b4b7-d97aa5274f73"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"
